import numpy as np
from sklearn.isotonic import IsotonicRegression
from collections import deque
import threading
from numba import njit

@njit
def fast_isotonic_inference(x_test: float, x_thresholds: np.ndarray, y_values: np.ndarray) -> float:
    """
    O(log N) inference using binary search on the piecewise constant 
    function generated by isotonic regression.
    """
    if x_test <= x_thresholds[0]:
        return y_values[0]
    if x_test >= x_thresholds[-1]:
        return y_values[-1]
    
    # Binary search
    low = 0
    high = len(x_thresholds) - 1
    
    while low <= high:
        mid = (low + high) // 2
        if x_thresholds[mid] == x_test:
            return y_values[mid]
        elif x_thresholds[mid] < x_test:
            low = mid + 1
        else:
            high = mid - 1
            
    return y_values[low - 1]

class LowLatencyRollingIsotonicCalibrator:
    """
    Calibrador de probabilidades usando regresión isotónica con ventana rodante.
    Optimizado para ultra-baja latencia mediante Numba e inferencia binaria.
    Incluye desacoplamiento por hilos para evitar picos de latencia.
    """
    def __init__(self, window_size: int = 5000):
        self.window_size = window_size
        self.margins = deque(maxlen=window_size)
        self.labels = deque(maxlen=window_size)
        self.model = IsotonicRegression(out_of_bounds='clip')
        
        # Parámetros para inferencia rápida (Numba)
        self.x_thresholds = np.array([-1e9, 1e9])
        self.y_values = np.array([0.5, 0.5])
        
        self.is_fitted = False
        self._lock = threading.Lock()
        self._updating = False

    def add_observation(self, margin: float, label: int):
        """
        Añade una nueva observación al buffer. Hilo-seguro.
        """
        with self._lock:
            self.margins.append(float(margin))
            self.labels.append(int(label))

    def update_calibration_curve(self):
        """
        Ejecuta el entrenamiento en el hilo actual (bloqueante).
        """
        if len(self.margins) < 100:
            return

        with self._lock:
            x = np.array(self.margins)
            y = np.array(self.labels)
        
        # El algoritmo PAVA de sklearn es O(N)
        new_model = IsotonicRegression(out_of_bounds='clip').fit(x, y)
        
        # Extraer puntos de interpolación para Numba
        # sklearn almacena los puntos únicos en X_thresholds_ e y_thresholds_
        # tras el fit en versiones recientes.
        with self._lock:
            self.model = new_model
            self.x_thresholds = self.model.X_thresholds_.copy()
            self.y_values = self.model.y_thresholds_.copy()
            self.is_fitted = True

    def update_in_background(self):
        """
        Inicia el re-entrenamiento en un hilo separado para no bloquear el path crítico.
        """
        if self._updating:
            return
        
        def target():
            self._updating = True
            try:
                self.update_calibration_curve()
            finally:
                self._updating = False
        
        thread = threading.Thread(target=target, daemon=True)
        thread.start()

    def calibrate_signal(self, margin: float) -> float:
        """
        Inferencia ultra-rápida usando el buscador binario Numba.
        """
        if not self.is_fitted:
            return 1.0 / (1.0 + np.exp(-margin))
        
        # Usamos los arrays de umbrales actuales (protegidos por copia en update)
        return fast_isotonic_inference(margin, self.x_thresholds, self.y_values)


if __name__ == "__main__":
    calibrator = LowLatencyRollingIsotonicCalibrator(window_size=1000)
    
    # Simular datos
    for _ in range(500):
        m = np.random.randn()
        l = 1 if m + np.random.randn() * 0.5 > 0 else 0
        calibrator.add_observation(m, l)
    
    calibrator.update_calibration_curve()
    
    test_margin = 1.5
    prob = calibrator.calibrate_signal(test_margin)
    print(f"Margen: {test_margin} -> Probabilidad Calibrada: {prob:.4f}")
